Contributing
Noders/Meetups pull request #38
Opened 2017-06-08 22:01 UTC by fforres

2017-06-09 02:14 UTC, Xabadu requested changes
Half 🍪 . If you want the other half, changes requested :)

2017-06-09 02:14 UTC, Xabadu commented on ISSUE_TEMPLATE.md
> +<!-- Con 20 palabras estamos bién :) -->
bien

2017-06-09 02:14 UTC, Xabadu commented on ISSUE_TEMPLATE.md
> +## ¿Cual es el título de tu charla?
Cuál

2017-06-09 02:14 UTC, Xabadu commented on ISSUE_TEMPLATE.md
> +## ¿Cual es tu nombre?
Cuál

2017-06-09 02:14 UTC, Xabadu commented on ISSUE_TEMPLATE.md
> +'Introduccíon al desarrollo con ReactJS'
Introducción

2017-06-09 02:14 UTC, Xabadu commented on ISSUE_TEMPLATE.md
> +##Quieres agregar algo más?
¿  y espacio

2017-06-09 14:59 UTC, fforres commented
I need a `.md` spellchecker :p
@Xabadu

2017-06-09 23:04 UTC, Xabadu commented on ISSUE_TEMPLATE.md
> +> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma página 😊
Nitpick/Non-blocker: Esta frase suena un poco rara en español. Es traducción literal the "on the same page"?

2017-06-09 23:05 UTC, Xabadu approved these changes

2017-06-10 00:09 UTC, fforres commented on ISSUE_TEMPLATE.md
> +> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma página 😊
Indeed.
Que tal algo en plan: 
Estamos en la misma onda?
Compartes nuestra visión?
Si compartes nuestra onda? 
Estamos de acuerdo?

2017-06-10 00:32 UTC, Xabadu commented on ISSUE_TEMPLATE.md
> +> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma página 😊
La primera me tinca bastante. La de 'nuestra visión/nuestra onda' puede sonar media impositiva.

2017-06-10 00:43 UTC, fforres commented on ISSUE_TEMPLATE.md
> +> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma página 😊
Osom 👍

2017-06-10 00:54 UTC, fforres commented
CC @Noders/meetup

2017-06-12 15:00 UTC, merged