Agregar Meetup checklist.md
Noders/Meetups pull request #39
Opened 2017-06-09 18:57 UTC by fforres

2017-06-09 19:02 UTC, DMaster69 commented on meetup_checklist.md
> +  - [ ] s
s?

2017-06-09 19:02 UTC, DMaster69 commented on meetup_checklist.md
> + - [ ] (?) Hablar con AxiomZen para pedir ['el gato'](https://www.elgato.com/en/gaming/game-capture-hd60-s).
Cuando no este @fforres  igual aplica este punto?, tenemos contacto ? condiciones / restricciones para el préstamo de este ?

2017-06-09 19:03 UTC, fforres commented on meetup_checklist.md
> + - [ ] (?) Hablar con AxiomZen para pedir ['el gato'](https://www.elgato.com/en/gaming/game-capture-hd60-s).
por eso le puse un `(?)` 
Voy a dejarlo conversado con AZ por si pueden prestarlo derepente :) 
Les comento

2017-06-09 19:03 UTC, fforres commented on meetup_checklist.md
> +  - [ ] s
s de ... 'sorry' 😄 
Lo updateo en 2 mins

2017-06-09 19:56 UTC, fforres commented
cc @Noders/meetup

2017-06-09 23:15 UTC, Xabadu requested changes
Half 🍪 again.

2017-06-09 23:15 UTC, Xabadu commented on meetup_checklist.md
> +  - [ ] Que sea relativamente accequible
accesible o asequible

2017-06-09 23:15 UTC, Xabadu commented on meetup_checklist.md
> +- [ ] Updatear las comunicaciones.
Actualizar instead of Updatear :)

2017-06-09 23:15 UTC, Xabadu commented on meetup_checklist.md
> +  - [ ] Otros grupos de facebook relevantes (proin, frontend chile, react chile, etc).
*Facebook - (PROIN, Frontend Chile, React Chile, etc.)

2017-06-09 23:15 UTC, Xabadu commented on meetup_checklist.md
> + - [ ] (?) Grabar la presentación con un celular o una camara web.
cámara

2017-06-09 23:15 UTC, Xabadu commented on meetup_checklist.md
> +  - [ ] Tener un mac/pc disponible donde bajar el codigo y correr demos
código

2017-06-09 23:15 UTC, Xabadu commented on meetup_checklist.md
> +- [ ] Subir el video a youtube.
YouTube

2017-06-09 23:15 UTC, Xabadu commented on meetup_checklist.md
> +  - [ ] Adjuntar el link al video de youtube.
YouTube

2017-06-09 23:15 UTC, Xabadu commented on meetup_checklist.md
> +        Preguntas abiertas, o que se enfoquen en la opinion del charlista, o preguntas con una solución simple pero extensible.
opinión

2017-06-09 23:15 UTC, Xabadu commented on meetup_checklist.md
> +        La idea es que el charlista pueda extenderse a gusto en una parada más de conversación/opinion.
opinión

2017-06-09 23:15 UTC, Xabadu commented on meetup_checklist.md
> +        - (Aplausos espontaneos para bajar del escenario)
espontáneos

2017-06-09 23:15 UTC, Xabadu commented on meetup_checklist.md
> +        - Que sigas el codigo de conducta [codigo de conducta](github.com/noders/code_of_conduct)
código

2017-06-09 23:15 UTC, Xabadu commented on meetup_checklist.md
> +1. Hablar del codigo de conducta.
código

2017-06-09 23:15 UTC, Xabadu commented on meetup_checklist.md
> +    - El codigo de conducta está en: [http://github.com/noders/code_of_conduct](github.com/noders/code_of_conduct), asi que si hay algo que no estén de acuerdo o quisieran mejorar, se aceptan PRs
código

2017-06-10 00:49 UTC, fforres commented
3 updates.
- Fixes ortograficos
- Eliminando files de entorno de desarrollo
- Agregando `.gitignore`

2017-06-10 01:08 UTC, Xabadu commented on .gitignore
> +node_modules
Newline please and thank you.

2017-06-10 01:08 UTC, Xabadu commented on meetup_checklist.md
> +  - [ ] Otros grupos de Facebook relevantes (proin, frontend chile, react chile, etc).
Titlecase/Uppercase para los nombres de los grupos, siglas?

2017-06-10 01:48 UTC, fforres commented on meetup_checklist.md
> +  - [ ] Otros grupos de Facebook relevantes (proin, frontend chile, react chile, etc).
... And links 👍

2017-06-10 01:48 UTC, fforres commented on .gitignore
> +node_modules
ok, pero es un poco nitpicking iguols o no?

2017-06-10 05:36 UTC, Xabadu commented on .gitignore
> +node_modules
Not really. No es un ultra mega big deal, pero hay algunos editores que tienen problemas generando los diffs cuando no hay newline al final, por eso GitHub te los remarca, pero como te decía, no es big deal, así que siéntete libre de ignorar este comentario.

2017-06-10 05:37 UTC, Xabadu approved these changes

2017-06-10 14:15 UTC, fforres commented on .gitignore
> +node_modules
Si, lo agregué al final NVM 😄

2017-06-10 14:15 UTC, merged